---
- name: Create AWS instances
  hosts: localhost
  tasks:

  - name: Create instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      key_name: user18kp
      region: us-east-1
      instance_type: t2.micro
      security_group: user18sg
      network_interfaces:
       - assign_public_ip: true
      image_id: ami-0a0e5d9c7acc336f1
      wait: yes
      state: running
    with_items:
      - build
      - deploy

  - name: Get instance information
    amazon.aws.ec2_instance_info:
      region: us-east-1
      filters:
        instance-state-name: ["pending", "running"]
    register: ec2

  # - name: Wait
  #   wait_for:
  #     timeout: 240

- name: Provision build host and build app
  hosts: build
  become: yes
  tasks:

  - name: Ensure git and maven are installed
    apt:
      name:
        - git
        - maven
      state: present
      update_cache: true
