---
- name: Create AWS instances
  hosts: localhost
  tasks:

  - name: Create instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      key_name: user18kp
      region: us-east-1
      instance_type: t2.micro
      security_group: user18sg
      network_interfaces:
       - assign_public_ip: true
      image_id: ami-0a0e5d9c7acc336f1
      wait: yes
      state: running
    with_items:
      - build
      - deploy

  - name: Refresh inventory to ensure new instance data exist in inventory
    meta: refresh_inventory

- name: Provision build host and build app
  hosts: build
  become: yes
  tasks:

  - name: Ensure git and maven are installed
    apt:
      name:
        - git
        - maven
      state: present
      update_cache: true

  - name: Clone app repo
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /src/boxfuse-sample-java-war-hello

  - name: Build app
    shell:
      chdir: /src/boxfuse-sample-java-war-hello
      cmd: mvn package

  - name: Retrieve build artifact from build
    fetch:
      src: /src/boxfuse-sample-java-war-hello/target/hello-1.0.war
      flat: true
      dest: /tmp/

- name: Provision deploy host and deploy app
  hosts: deploy
  become: yes
  tasks:

  - name: Ensure Tomcat is installed
    apt:
      name: tomcat9
      state: present
      update_cache: true

  - name: Ensure Tomcat service is running
    service:
      name: tomcat9
      state: started

  - name: Copy build artifact to deploy
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
    notify: Restart Tomcat

  handlers:
  - name: Restart Tomcat
    service:
      name: tomcat9
      state: restarted

