---
- name: Create AWS EC2 instances and configure them
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Launch EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: user18kp
      region: us-east-1
      instance_type: t2.micro
      security_group: user18sg
      network_interfaces:
       - assign_public_ip: true
      image_id: ami-0a0e5d9c7acc336f1
      wait: yes
      tags:
        Name: "{{ item.name }}"
    loop:
      - { name: "build" }
      - { name: "deploy" }

- name: Install packages on build instance
  hosts: tag_Name_build
  become: yes
  tasks:
    - name: Install git and maven
      apt:
        name:
          - git
          - maven
        state: present

- name: Install tomcat on deploy instance
  hosts: tag_Name_deploy
  become: yes
  tasks:
    - name: Install tomcat
      apt:
        name: tomcat
        state: present
