---
- hosts: localhost
  gather_facts: no
  vars_files:
    - secrets.yml

  - name: Set AWS credentials for dynamic inventory
    set_fact:
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_key }}"

  - name: Start instances
    amazon.aws.ec2_instance:
      name: {{ item }}
      key_name: user18kp
      instance_type: t2.micro
      security_group: user18sg
      network_interfaces:
       - assign_public_ip: true
      image_id: ami-0a0e5d9c7acc336f1
    with_items:
      - build
      - deploy