---
- name: Create AWS instances
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Create instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      key_name: user18kp
      region: us-east-1
      instance_type: t2.micro
      security_group: user18sg
      network_interfaces:
       - assign_public_ip: true
      image_id: ami-0a0e5d9c7acc336f1
      wait: yes
      state: running
    with_items:
      - build
      - deploy
    register: ec2
    
  - name: Wait for SSH connectivity
    wait_for_connection:
      host: "{{ item.public_ip_address }}"
      state: started
      delay: 5
      timeout: 60
    with_items:
      - "{{ ec2.instances }}"

- name: Provision build host and build app
  hosts: build
  become: yes
  tasks:

  - name: Ensure git and maven are installed
    apt:
      name:
        - git
        - maven
      state: present
      update_cache: true
